routes/web.php
<?php

use App\Http\Controllers\CSV\ExportController;
use App\Http\Controllers\CSV\ImportController;
use App\Http\Controllers\Main\ContactController;
use App\Http\Controllers\Main\IndexController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [IndexController::class, 'index'])->middleware('guest');
Route::group(['middleware' => 'auth'], function () {
    Route::get('/search', [IndexController::class, 'search'])->name('search');
    Route::resource('contacts', ContactController::class)->except('show');
    Route::post('/import', [ImportController::class, 'import'])->name('import');
    Route::get('/export', [ExportController::class, 'export'])->name('export');
});

Auth::routes();

Route::fallback(function () {
    return redirect()->to('/contacts');
});

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Contact extends Model
{
    use HasFactory;

    protected $table = 'contacts';
    protected $fillable = [
        'user_id',
        'name',
        'surname',
        'phone',
        'identifier'
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Api/V1/ContactController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\Contact\StoreRequest;
use App\Http\Requests\Api\Contact\UpdateRequest;
use App\Http\Resources\Contact\ContactResource;
use App\Models\Contact;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request): AnonymousResourceCollection
    {
        $id = $request->user()->id;
        $contacts = Contact::query()->where('user_id', $id)->get();

        return ContactResource::collection($contacts);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRequest $request): ContactResource
    {
        $data = $request->validated();
        $data['phone'] = (string) $data['phone'];
        $contact = Contact::query()->create($data);

        return new ContactResource($contact);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Contact $contact): ContactResource
    {
        return new ContactResource($contact);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateRequest $request, Contact $contact): ContactResource
    {
        $data = $request->validated();
        $data['phone'] = (string) $data['phone'];
        $contact->update($data);

        return new ContactResource($contact);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Contact $contact): JsonResponse
    {
        $contact->delete();

        return response()->json([
            'status' => true,
            'message' => 'Contact deleted',
        ]);
    }
}

app/Http/Controllers/Main/ContactController.php
<?php

namespace App\Http\Controllers\Main;

use App\Http\Controllers\Controller;
use App\Http\Requests\Contact\StoreRequest;
use App\Http\Requests\Contact\UpdateRequest;
use App\Models\Contact;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $contacts = Contact::query()
            ->where('user_id', auth()->id())
            ->paginate(3);
        return view('contacts.index', compact('contacts'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRequest $request): RedirectResponse
    {
        $data = $request->validated();
        $data['user_id'] = auth()->id();
        $data['phone'] = (string) $data['phone'];
        Contact::query()->create($data);
        return redirect()->route('contacts.index');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Contact $contact): View
    {
        return view('contacts.edit', compact('contact'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateRequest $request, Contact $contact): RedirectResponse
    {
        $data = $request->validated();
        $data['phone'] = (string) $data['phone'];
        $contact->update($data);
        return redirect()->route('contacts.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Contact $contact): RedirectResponse
    {
        $contact->delete();
        return redirect()->route('contacts.index');
    }
}

resources/views/contacts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Изменить запись') }}</div>

                    <div class="card-body">
                        <form action="{{ route('contacts.update', $contact->id) }}" method="POST">
                            @csrf
                            @method('PATCH')
                            <div class="form-group">
                                <input name="name" placeholder="Имя" class="form-control mb-2" value={{ $contact->name }}>
                                @error('name')
                                <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <input name="surname" placeholder="Фамилия" class="form-control mb-2" value={{ $contact->surname }}>
                                @error('surname')
                                <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <input name="phone" placeholder="Телефон" class="form-control mb-2" value={{ $contact->phone }}>
                                @error('phone')
                                <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-primary">Изменить</button>
                        </form>
                        <form action="{{ route('contacts.destroy', $contact->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger mt-2">Удалить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/contacts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form action="{{ route('search') }}" method="GET" class="mb-2">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Поиск"
                               aria-label="Recipient's username" aria-describedby="button-addon2" name="search">
                        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Найти</button>
                    </div>
                    @error('search')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </form>
                <div class="card">
                    <div class="card-header">{{ __('Добавить запись') }}</div>

                    <div class="card-body">
                        <form action="{{ route('contacts.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <input name="name" placeholder="Имя" class="form-control mb-2">
                                @error('name')
                                <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <input name="surname" placeholder="Фамилия" class="form-control mb-2">
                                @error('surname')
                                <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <input name="phone" placeholder="Телефон" class="form-control mb-2">
                                @error('phone')
                                <div class="text-danger">{{ $message }}</div>
                                @enderror
                                @error('identifier')
                                <div class="text-danger">This phone number already exists</div>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-primary float-right">Добавить</button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 my-2">
                <hr>
            </div>
        </div>
    </div>

    @if($contacts->count() > 0)
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @foreach($contacts as $contact)
                        <div class="card mb-2">

                            <div class="card-header d-flex justify-content-between">
                                <div>
                                    {{ $contact->name }} {{ $contact->surname }}
                                </div>
                                <div>
                                    <a href="{{ route('contacts.edit', $contact->id) }}"
                                       class="link-underline link-underline-opacity-0">&#9998;</a>
                                </div>
                            </div>
                            <div class="card-body">
                                {{ $contact->phone }}
                            </div>

                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    @else
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <p>У Вас нет записей.</p>
                </div>
            </div>
        </div>
    @endif

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 my-2">
                {{ $contacts->links() }}
            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Загрузить данные</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="import" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="input-group mb-3">
                            <input type="file" name="file" class="form-control">
                            <button class="btn btn-primary" type="submit">Загрузить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



@endsection